[package]
name = "openadr-rs"
version = "0.1.0"
edition = "2021"
rust-version = "1.70" # MSRV
license = "Apache-2.0 OR MIT"
repository = "https://github.com/tweedegolf/openadr-rs"
homepage = "https://github.com/tweedegolf/openadr-rs"
publish = true
description = "An OpenADR 3.0 VTN/VEN implementation"

[dependencies]
reqwest = { version = "0.12.4", default-features = false, features = ["http2", "charset", "rustls-tls-native-roots"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["full"] }

[lib]
name = "openadr"

[[bin]]
name = "vtn"
path = "src/vtn/main.rs"

[[bin]]
name = "openadr"
path = "src/cli/main.rs"
