[graph]
targets = [
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
]

[licenses]
version = 2
private = { ignore = true }
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
]
